"""Add actor age

Revision ID: 4328388afa62
Revises: d852e4533074
Create Date: 2020-03-30 19:31:53.300168

"""
from alembic import op
from sqlalchemy import CheckConstraint
from models import MIN_ACTOR_AGE, MAX_ACTOR_AGE
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4328388afa62'
down_revision = 'd852e4533074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('age', sa.SmallInteger(), CheckConstraint(f'age > {MIN_ACTOR_AGE} AND age < {MAX_ACTOR_AGE}'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actors', 'age')
    # ### end Alembic commands ###
