"""Initial commit

Revision ID: c533df43b3b6
Revises: 
Create Date: 2020-03-27 01:00:46.163301

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func
from datetime import datetime


# revision identifiers, used by Alembic.
revision = 'c533df43b3b6'
down_revision = None
branch_labels = None
depends_on = None

gender = sa.Enum('m', 'f', name='gender')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gender', gender, nullable=False, server_default='m'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('release_date', sa.DateTime(), server_default=func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actors_movies',
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('actor_id', 'movie_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actors_movies')
    op.drop_table('movies')
    op.drop_table('actors')
    gender.drop(op.get_bind())
    # ### end Alembic commands ###
