"""Initial commit

Revision ID: d852e4533074
Revises: 
Create Date: 2020-03-29 13:19:30.888015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from models import MAX_ACTOR_NAME_LENGTH

revision = 'd852e4533074'
down_revision = None
branch_labels = None
depends_on = None

gender = sa.Enum('m', 'f', name='gender')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(MAX_ACTOR_NAME_LENGTH), nullable=False),
    sa.Column('gender', gender, server_default='m', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(100), nullable=False),
    sa.Column('release_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actors_movies',
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('actor_id', 'movie_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actors_movies')
    op.drop_table('movies')
    op.drop_table('actors')
    gender.drop(op.get_bind())
    # ### end Alembic commands ###
